### ISSUE TITLE
add "admin/moderator" interface and components (so can cleanup nasty chans)

### ISSUE THREAD

**Issue by 4www** [radio4000/supabase#17]

**Comment by oskarrough** [comment]
Do we want the SQL deletes to cascade on auth.user here? So if you delete a user, all channels and tracks also go? As long as we don't have users sharing radios we could do it.

**Comment by oskarrough** [comment]
> Do we want the SQL deletes to cascade on auth.user here? So if you delete a user, all channels and tracks also go? As long as we don't have users sharing radios we could do it.

https://github.com/radio4000/supabase/pull/24 implements the above.

And here is a WIP component https://github.com/radio4000/supabase/issues/17
